"""Add active column to Product

Revision ID: 891d33fe4ff3
Revises: 0177dbcdf45b
Create Date: 2025-12-11 21:43:22.080198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '891d33fe4ff3'
down_revision = '0177dbcdf45b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_categories_name'), ['name'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('active')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_categories_name'), type_='unique')

    # ### end Alembic commands ###
